"""create models

Revision ID: fb372fc9bba1
Revises: 
Create Date: 2023-06-13 14:29:42.474931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb372fc9bba1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol_id'),
    sa.UniqueConstraint('symbol_name')
    )
    op.create_table('candles',
    sa.Column('candle_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.symbol_id'], ),
    sa.PrimaryKeyConstraint('candle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles')
    op.drop_table('symbols')
    # ### end Alembic commands ###
